INSERT INTO PYX_ACOLITO (SN_CERIMONIARIO, DT_NASCIMENTO, DT_NOMEACAO, DS_EMAIL, DS_NOME, DS_SENHA, DS_SOBRENOME, DS_TELEFONE, DS_USUARIO)
VALUES ('S', '2001-03-09', '2011-08-08', 'admin@pyxis.com', 'Gabriel', 'senha', 'Martins', '11978237823', 'gmartins');

INSERT INTO PYX_ACOLITO (SN_CERIMONIARIO, DT_NASCIMENTO, DT_NOMEACAO, DS_EMAIL, DS_NOME, DS_SENHA, DS_SOBRENOME, DS_TELEFONE, DS_USUARIO)
VALUES ('N', '2005-07-19', '2018-07-07', 'maria.vitoria@pyxis.com', 'Maria Vitoria', 'senha', 'Melo', '11956235623', 'mvmelo');

INSERT INTO PYX_RESPONSAVEL (DS_EMAIL, DS_NOME, DS_SOBRENOME, DS_TELEFONE)
VALUES ('ubiracir@gmail.com', 'Ubiracir', 'Melo', '11976347634');

INSERT INTO PYX_RESPONSAVEL_DEPENDENTE (RESPONSAVEL_ID, DEPENDENTE_ID)
VALUES (1, 2);

-- DH_ESCALA, SN_QUARTA_FEIRA, DS_EMAIL, DS_NOME, DS_SOBRENOME, DS_TELEFONE, ACOLITO_ID